"""create description column

Revision ID: 146770ab2446
Revises: 2f9a33b93b1b
Create Date: 2023-12-06 19:42:14.828611

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '146770ab2446'
down_revision = '2f9a33b93b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discs', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
